name: CI

on: [push]

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run test
              npm run lint
              npm run type-check
              npm run build