name: CI

on: [push]

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: |
          yarn test
          yarn lint
          yarn type-check
          yarn build:lib